-- ============================================================================
-- Encore demo reset — GENERATED by seed/build-seed.ts. Do not edit by hand.
-- Restores Andrew (00000000-0000-4000-a000-000000000001) to the canonical
-- 15-show pre-demo ladder: deletes the live-logged show (Fred again.. at
-- Forest Hills) + its comparisons, restores rank/score/note/moment, resets
-- tier cuts. Idempotent. Run: npm run demo:reset
-- ============================================================================
begin;

-- live comparisons are stamped after the seed cutoff
delete from comparisons
 where user_id = '00000000-0000-4000-a000-000000000001'
   and created_at > '2026-07-17 00:00:00+00';

-- drop any set_log that is not one of the 15 canonical rows (Fred + strays)
delete from set_logs
 where user_id = '00000000-0000-4000-a000-000000000001'
   and id not in (
     'e13f3d36-a3fe-5325-a6a9-0db08cd39795',
     'bf1902f1-4847-542c-8863-231f6e759664',
     '4af20ab9-a322-50a5-8c94-2467c130b1db',
     '24d746fc-043f-5b3b-9eee-fd63ecc93be3',
     '26aa52a4-9cdd-5d6e-9191-edc0f65a303d',
     '770c1774-e803-5a6d-8060-885846371e09',
     '4d68ab68-8b34-5597-a0d6-2b51e9b3e945',
     '05a24374-885d-542e-9411-ec5ac16f0c39',
     'a3701da6-cd9c-562e-8ab3-45f3313edc44',
     'e3a06755-ef81-57bb-8611-1960e29e3e3c',
     'a1377db0-09ac-52d5-b4ce-8abab8dce66d',
     'f617fbf2-0071-5b4b-a252-f6374db23df6',
     '2a48699e-a88e-526a-b110-d4425f974348',
     '65baf3da-0a12-53a3-b25b-3936fcafcff8',
     '6be5b43e-6907-5ee2-be89-83f8172e74c4'
   );

-- restore canonical rank_pos / latent_score / note / moment
update set_logs as sl
   set rank_pos = v.rank_pos,
       latent_score = v.latent_score,
       note = v.note,
       moment = v.moment::moment_tag
  from (values
    ('e13f3d36-a3fe-5325-a6a9-0db08cd39795'::uuid, 1, 1808::double precision, 'Innerbloom closer. Grown men crying everywhere.', 'the_encore'),
    ('bf1902f1-4847-542c-8863-231f6e759664'::uuid, 2, 1766::double precision, null, 'the_visuals'),
    ('4af20ab9-a322-50a5-8c94-2467c130b1db'::uuid, 3, 1728::double precision, 'Best crowd of my life, under an actual bridge.', 'the_crowd'),
    ('24d746fc-043f-5b3b-9eee-fd63ecc93be3'::uuid, 4, 1638::double precision, null, null),
    ('26aa52a4-9cdd-5d6e-9191-edc0f65a303d'::uuid, 5, 1600::double precision, null, null),
    ('770c1774-e803-5a6d-8060-885846371e09'::uuid, 6, 1560::double precision, null, null),
    ('4d68ab68-8b34-5597-a0d6-2b51e9b3e945'::uuid, 7, 1516::double precision, null, null),
    ('05a24374-885d-542e-9411-ec5ac16f0c39'::uuid, 8, 1426::double precision, null, null),
    ('a3701da6-cd9c-562e-8ab3-45f3313edc44'::uuid, 9, 1388::double precision, null, 'the_drop'),
    ('e3a06755-ef81-57bb-8611-1960e29e3e3c'::uuid, 10, 1348::double precision, null, null),
    ('a1377db0-09ac-52d5-b4ce-8abab8dce66d'::uuid, 11, 1258::double precision, null, null),
    ('f617fbf2-0071-5b4b-a252-f6374db23df6'::uuid, 12, 1218::double precision, null, null),
    ('2a48699e-a88e-526a-b110-d4425f974348'::uuid, 13, 1180::double precision, null, null),
    ('65baf3da-0a12-53a3-b25b-3936fcafcff8'::uuid, 14, 1090::double precision, null, null),
    ('6be5b43e-6907-5ee2-be89-83f8172e74c4'::uuid, 15, 1052::double precision, 'Too hard for a school night. My fault.', null)
  ) as v(id, rank_pos, latent_score, note, moment)
 where sl.id = v.id;

-- reset tier cuts to the seeded auto-buckets
update profiles
   set tier_bounds = '{"cuts":[3,7,10,13]}'::jsonb
 where id = '00000000-0000-4000-a000-000000000001';

commit;
